# The language identifier of the language used in the source code for `gettext` and `fluent` systems
fallback_language = "en"

# The gettext domain for your project
[gettext]
domain = "gitlab-todo-indicator"
target_languages = ["en"]
output_dir = "po"

[fluent]
assets_dir = "i18n"